### ISSUE TITLE
Ritiro presso il punto vendita / individuazione dei cittadini bisognosi di consegna a domicilio

### ISSUE THREAD

**Issue by Nittitaly** [magomimmo/insieme#5]
1) chi ha una certificazione di invalidità ex. L 104 
2I https://www.linkedin.com/in/ferdinando-acerbi-b52555a Ferdinando Acerbi è molto competente in questo ambito perché ha creato un'app che permette ai portatori di handicap ex L. 104 di avere accesso alle ZTL in tutta italia previo caricamento dei titoli che ne danno diritto 
3) le associazioni possono aiutare in questo senso (ho una collega non vedente molto attiva, lei può dare indicazioni) 
3) per gli anziani non portatori di handicap  ai quali si richiede di non uscire si può chiedere l'indicazione di un documento

**Comment by magomimmo** [comment]
assorbito primo punto e messo in nota il secondo. ho visto che stai cercando i contatto su linkeid. chiudo l'issue per il momento.
